// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLNQnjkn6Emktz4AXcdWGRbKecxy4cHJs',
    appId: '1:561577093024:web:ad17f2efc74cc5ac85a6c5',
    messagingSenderId: '561577093024',
    projectId: 'campusconnect-firebase-6af72',
    authDomain: 'campusconnect-firebase-6af72.firebaseapp.com',
    storageBucket: 'campusconnect-firebase-6af72.firebasestorage.app',
    measurementId: 'G-ZD0D92E9V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcGPQtpb9z-BguSD0Qdube9D0_MbqnjPM',
    appId: '1:561577093024:android:ff0a4c8dc0909a0a85a6c5',
    messagingSenderId: '561577093024',
    projectId: 'campusconnect-firebase-6af72',
    storageBucket: 'campusconnect-firebase-6af72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEhCv3uzzrHt52DJBS9RUmriDB5J-bKF0',
    appId: '1:561577093024:ios:6e6357c501c59b5085a6c5',
    messagingSenderId: '561577093024',
    projectId: 'campusconnect-firebase-6af72',
    storageBucket: 'campusconnect-firebase-6af72.firebasestorage.app',
    iosBundleId: 'com.example.campusconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEhCv3uzzrHt52DJBS9RUmriDB5J-bKF0',
    appId: '1:561577093024:ios:6e6357c501c59b5085a6c5',
    messagingSenderId: '561577093024',
    projectId: 'campusconnect-firebase-6af72',
    storageBucket: 'campusconnect-firebase-6af72.firebasestorage.app',
    iosBundleId: 'com.example.campusconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLNQnjkn6Emktz4AXcdWGRbKecxy4cHJs',
    appId: '1:561577093024:web:7372e9c765c20e4b85a6c5',
    messagingSenderId: '561577093024',
    projectId: 'campusconnect-firebase-6af72',
    authDomain: 'campusconnect-firebase-6af72.firebaseapp.com',
    storageBucket: 'campusconnect-firebase-6af72.firebasestorage.app',
    measurementId: 'G-QWJBXDRB2G',
  );
}
